FROM golang:1.21 as builder
WORKDIR /build
ENV GOPROXY=https://proxy.golang.org
COPY go.mod . 
COPY go.sum . 
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./cmd/app/main.go

FROM alpine
COPY --from=builder main /bin/main
ENTRYPOINT ["/bin/main"]