// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/ports/storage/person.go

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	dto "people_service/internal/domain/dto"
	model "people_service/internal/domain/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPersonStorage is a mock of PersonStorage interface.
type MockPersonStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPersonStorageMockRecorder
}

// MockPersonStorageMockRecorder is the mock recorder for MockPersonStorage.
type MockPersonStorageMockRecorder struct {
	mock *MockPersonStorage
}

// NewMockPersonStorage creates a new mock instance.
func NewMockPersonStorage(ctrl *gomock.Controller) *MockPersonStorage {
	mock := &MockPersonStorage{ctrl: ctrl}
	mock.recorder = &MockPersonStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonStorage) EXPECT() *MockPersonStorageMockRecorder {
	return m.recorder
}

// AddPerson mocks base method.
func (m *MockPersonStorage) AddPerson(arg0 context.Context, arg1 *dto.AddPersonDTO) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPerson", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPerson indicates an expected call of AddPerson.
func (mr *MockPersonStorageMockRecorder) AddPerson(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPerson", reflect.TypeOf((*MockPersonStorage)(nil).AddPerson), arg0, arg1)
}

// DeletePerson mocks base method.
func (m *MockPersonStorage) DeletePerson(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePerson", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePerson indicates an expected call of DeletePerson.
func (mr *MockPersonStorageMockRecorder) DeletePerson(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePerson", reflect.TypeOf((*MockPersonStorage)(nil).DeletePerson), arg0, arg1)
}

// GetPerson mocks base method.
func (m *MockPersonStorage) GetPerson(arg0 context.Context, arg1 int64) (*model.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPerson", arg0, arg1)
	ret0, _ := ret[0].(*model.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPerson indicates an expected call of GetPerson.
func (mr *MockPersonStorageMockRecorder) GetPerson(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPerson", reflect.TypeOf((*MockPersonStorage)(nil).GetPerson), arg0, arg1)
}

// GetPersons mocks base method.
func (m *MockPersonStorage) GetPersons(arg0 context.Context, arg1 *dto.PersonsGetDTO) ([]model.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersons", arg0, arg1)
	ret0, _ := ret[0].([]model.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersons indicates an expected call of GetPersons.
func (mr *MockPersonStorageMockRecorder) GetPersons(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersons", reflect.TypeOf((*MockPersonStorage)(nil).GetPersons), arg0, arg1)
}

// UpdatePerson mocks base method.
func (m *MockPersonStorage) UpdatePerson(arg0 context.Context, arg1 *dto.UpdatePersonDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePerson", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePerson indicates an expected call of UpdatePerson.
func (mr *MockPersonStorageMockRecorder) UpdatePerson(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePerson", reflect.TypeOf((*MockPersonStorage)(nil).UpdatePerson), arg0, arg1)
}
